Fixed django compatibility
douglasfarinelli/python-cachelock pull request #7
Opened 2021-01-11 10:10 UTC by Galtozzy

2021-01-12 20:26 UTC, douglasfarinelli requested changes

2021-01-12 20:26 UTC, douglasfarinelli commented on cachelock.py
> +    from django.core.cache import caches
Hi @Galtozzy! Thanks for contributing! 

I'm sorry for the delay in replying, unfortunately I didn't have much time.

My only point is that it would be interesting to deal with previous versions of Django. What do you think?

```python
try:
    from django.core.cache import caches
except ModuleNotFoundError:
    from django.core.cache import cache as caches
```

2021-01-12 22:39 UTC, Galtozzy commented on cachelock.py
> +    from django.core.cache import caches
Hi @douglasfarinelli! Thanks for you reply.
I've pushed out a small fix. That should work for lower versions as well.

2021-01-13 20:05 UTC, douglasfarinelli commented on cachelock.py
> +    from django.core.cache import caches
Hi @Galtozzy!

Better validating the code, I believe that this proposed implementation should not work.

The [cache](https://github.com/django/django/blob/master/django/core/cache/__init__.py#L49) object does not have the [`__getitem__`](https://github.com/django/django/blob/master/django/core/cache/__init__.py#L49) method using the [line below](https://github.com/douglasfarinelli/python-cachelock/blob/master/cachelock.py#L63). :(

2021-01-13 21:12 UTC, Galtozzy commented on cachelock.py
> +    from django.core.cache import caches
Sorry, it's my bad I haven't tested it on a lower versions. 
Rewrote that a bit different and tested it in both Python2.7 Django=1.6.5 and in latest 3.9 with Django>3

2023-12-19 19:05 UTC, closed without merging